test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_summation
    output = exercice.prime_integer_summation()
  File "/home/runner/work/c03_ch5_exercices-simonhache/c03_ch5_exercices-simonhache/exercice.py", line 27, in prime_integer_summation
    if i%n != 0:
ZeroDivisionError: integer division or modulo by zero

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=1)
